### ISSUE TITLE
Reproducing sampling for alanine dipeptide

### ISSUE THREAD

**Issue by ghost** [weiHelloWorld/accelerated_sampling_with_autoencoder#61]
Hi Wei,
I'm having troubles reproducing your results for alanine dipeptide using this MESA program. I am running the exact same parameters as stated in your paper Molecular Enhanced Sampling with Autoencoders: On-The-Fly Collective Variable Discovery and Accelerated Free Energy Landscape Exploration, with the package versions, and program on this page. After running 10 iterations you show the following plot in the paper: 
![paper](https://user-images.githubusercontent.com/37177062/48945260-f51fce00-ef29-11e8-9591-3976ff2116e0.png)

Though after i run 10 iterations i get the following plots: 
![capture](https://user-images.githubusercontent.com/37177062/48945315-24ced600-ef2a-11e8-9339-f82eba900d3d.PNG)
Not nearly as converged. This is even after repeating several times a choosing the best. My plot is aggregated data of all biased simulations of 10 MESA iterations.

I am aware that the CV plots are not comparable since the exact autoencoders may be very different, even though my projection of the 4D flat torus is not nearly as distinct as yours. Despite this the amount of enhanced sampling in phi psi space should be comparable.

My question is whether you have many more biased simulations ? I have 7-9ish per iteration. How many datapoints do your plots contain? Have you also run the MESA procedure several times and picked the best run, as I?

With the hope of testing the method i really have to reproduce a converged MESA run of alanine dipeptide. I have tried increasing the number of iterations to 20, used reversed sorting, and force constants of 2000/4000, with no additional gain in sampling.

Best regards
Kasper Busk
Masters student
Aarhus University

**Comment by weiHelloWorld** [comment]
Hi Kasper,

I agree it is more difficult to sample configuration space of alanine dipeptide than many other systems (e.g. Trp-cage), due to intrinsic topology issue (the flat torus cannot be well projected in 2D space), as we discussed in the paper.  So unlike Trp-cage, it is not guaranteed that we always get good sampling within 10 iterations for alanine dipeptide.  To get good sampling, we need to make sure at each iteration, not only "boundary points" are selected as potential centers, we also need to select potential centers from "internal holes" (see iteration 3, 4, 6, 7, 8, 9, 10 in Fig. 7 of the paper).  Filling internal holes is especially important for alanine dipeptide due to its intrinsic periodic topology.  To improve sampling "internal holes", I suggest for later iterations you may either use smaller bins (for boundary detection algorithom), or use metadynamics directly.

For your questions:

1. whether you have many more biased simulations?

I used 15-20 biased simulations.  If the biased simulations in your MESA run can both explore the boundary and fill internal holes, that should be fine.

2.  How many datapoints do your plots contain?

I have 100 points per biased simulation, so 1500-2000 per iteration, 15000-20000 in 10 iterations.

3. Have you also run the MESA procedure several times and picked the best run, as I?

For alanine dipeptide, yes. For Trp-cage, I found results are very consistent.
